push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "run.xml";
push @generated_exts, "auxlock";
$clean_ext = "bbl aux cb2 cb spl nav snm tdo nmo brf nlg nlo nls run.xml auxlock";
set_tex_cmds( '--shell-escape %O %S' );
