#!/bin/bash

main() {
pathtorepo='/Users/mike/Documents/Studium/Master/Diplom'
reponame=${pathtorepo##*/}
pathtoremote='/Volumes/GITERIA/REPOS/'

cd $pathtoremote
git clone --mirror $pathtorepo'/' $reponame'.git/'
cd $pathtorepo
git remote add usb file://$pathtoremote/$reponame/
git fetch usb
git branch --set-upstream-to usb/master
}

main $@
